### ISSUE TITLE
Presente [invalid mirror] after executing [bash ~/Network-Reinstall-System-Modify.sh -CentOS_7]

### ISSUE THREAD

**Issue by Pyrokine** [MeowLove/Network-Reinstall-System-Modify#12]
You have chosen to install the latest CentOS_7 

Check Dependence

[ok]		iconv
[ok]		wget
[ok]		awk
[ok]		grep
[ok]		sed
[ok]		cut
[ok]		cat
[ok]		cpio
[ok]		gzip
[ok]		find
[ok]		dirname
[ok]		basename
Error! Invaild mirror! 
example: http://deb.debian.org/debian

 Usage:
	bash Core_Install.sh	-d/--debian [dists-name]
				-u/--ubuntu [dists-name]
				-c/--centos [dists-verison]
				-v/--ver [32/i386|64/amd64]
				--ip-addr/--ip-gate/--ip-mask
				-apt/-yum/--mirror
				-dd/--image
				-a/--auto
				-m/--manual
---------------------------------------------------------------------------------------------------------------------
 Start Installation 
 Start Installation 
---------------------------------------------------------------------------------------------------------------------

/root/Network-Reinstall-System-Modify.sh: line 77: i: command not found
---------------------------------------------------------------------------------------------------------------------
 Start Installation 
 Start Installation 
---------------------------------------------------------------------------------------------------------------------

**Comment by MeowLove** [comment]
Change the initial template from the service provider, or change the Mirrors source, as mentioned in my blog.

更换来自服务商的初始模板，或更换Mirrors源，我的博客有讲到。
