### ISSUE TITLE
运行脚本后安装系统选择u20，vnc查看需要收到设置ip地址

### ISSUE THREAD

**Issue by slmepipi** [MeowLove/Network-Reinstall-System-Modify#15]
运行脚本后安装系统选择u20，vnc查看需要收到设置ip地址

**Comment by slmepipi** [comment]
![企业微信截图_20210109155559](https://user-images.githubusercontent.com/29816608/104086458-44a0ef80-5293-11eb-84b5-e72218d81af8.png)
麻烦查看

**Comment by MeowLove** [comment]
换个源Mirrors，多试几个服务器自带的系统。然后可以手动设置好IP，手动指定IP。
