### ISSUE TITLE
unreachable gateway

### ISSUE THREAD

**Issue by liangxyz** [MeowLove/Network-Reinstall-System-Modify#17]
在rfchost vps上使用安装脚本，会提示unreachable gateway，安装进度卡死，通过vnc链接，选中continue并回车也还是这个页面
![image](https://user-images.githubusercontent.com/8108927/116172933-3ab9d400-a73e-11eb-8732-c5dfbca1c0bb.png)

**Comment by MeowLove** [comment]
https://github.com/MeowLove/Network-Reinstall-System-Modify/issues/13#issue-724376654
