### ISSUE TITLE
腾讯云轻量云报错没有grub.cfg

### ISSUE THREAD

**Issue by ykla** [MeowLove/Network-Reinstall-System-Modify#20]
已经grub2-mkconfig -o /boot/grub2/grub.cfg了，系统centos7。
仍然提示 Error grub.cfg

**Comment by ljm1447669873** [comment]
aws的ubuntu20.04 dd也会报错Error grub.cfg

**Comment by MeowLove** [comment]
问题已解决，请等待新版V5发布。。

重构的新版DD，修了很多Bug，兼容性更高，我想跟着Debian11一起发布，所以一直在等。
用Golang重写全套，更多新功能，基于Debain11底层，支持Win to Linux，Linux to ALL

当前V4版是基于Debian9底层的，想发新v5版，感觉Debian11快发布稳定版了，v5用Debian10做底层，后续万一要改，就麻烦。所以就直接上Debian11底层了
