### ISSUE TITLE
可否设置带自定义安装源？

### ISSUE THREAD

**Issue by zc0350** [MeowLove/Network-Reinstall-System-Modify#21]
使用这个脚本安装在外国服务器/VPS速度是非常快的，
然而使用在 阿里云，腾讯云上时，有时候速度很慢，检查网络的时候。发现软件 下载速度为 10多KB/s ~

如果能有一条自定义安装源（参数）的话。也许是很不错的方案，
当然也希望 自定义几条 官方版本的 安装源~ 这样方便小白~

**Comment by MeowLove** [comment]
新版已经发布，支持大陆优化
The new version has been released to support mainland optimization.
