### ISSUE TITLE
Not found interfaces config 如何解决

### ISSUE THREAD

**Issue by sdc9088** [MeowLove/Network-Reinstall-System-Modify#27]
[Debian] [stretch] [amd64] Downloading...
Error, Not found interfaces config.

**Comment by sdc9088** [comment]
开启root登入
sudo -I
cd /root

修改authorized_keys文件（即ssh证书）
vi .ssh/authorized_keys
把ssh-rsa之前的文件都删除掉.
编辑ssh配置文件
vi /etc/ssh/sshd_config
找到PermitRootLogin, 把前面的#去掉 改成下面这样
PermitRootLogin yes
 保存退出
reboot
重启服务器。就可以使用root用户名配合秘钥登入了

2:开启防火墙
iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -F
apt-get purge netfilter-persistent

reboot 重启

**Comment by MeowLove** [comment]
更换服务商的原系统，按照博客推荐的。
Replace the original system of the service provider, as recommended by the blog.

**Comment by peaceanddemocracy** [comment]
运行：

cat << 'EOF' > fix_interfaces.sh
#!/bin/bash

# 1. 获取默认路由的网卡名称
INTERFACE=$(ip route show default | awk '/default/ {print $5}')

# 2. 获取当前 IP 地址和掩码
IP_ADDR=$(ip addr show $INTERFACE | grep 'inet ' | awk '{print $2}' | cut -d/ -f1)
NETMASK_CIDR=$(ip addr show $INTERFACE | grep 'inet ' | awk '{print $2}' | cut -d/ -f2)

# 3. 获取网关
GATEWAY=$(ip route show default | awk '/default/ {print $3}')

# 将 CIDR 掩码转换为点分十进制 (如 24 -> 255.255.255.0)
mask2cidr() {
    local x=$(( 0xFFFFFFFF << (32 - $1) ))
    echo "$(( (x >> 24) & 0xFF )).$(( (x >> 16) & 0xFF )).$(( (x >> 8) & 0xFF )).$(( x & 0xFF ))"
}
NETMASK=$(mask2cidr $NETMASK_CIDR)

# 4. 写入文件
echo "正在检测网络配置..."
echo "网卡: $INTERFACE"
echo "IP: $IP_ADDR"
echo "掩码: $NETMASK"
echo "网关: $GATEWAY"

mkdir -p /etc/network
cat << EOT > /etc/network/interfaces
auto lo
iface lo inet loopback

auto $INTERFACE
iface $INTERFACE inet static
    address $IP_ADDR
    netmask $NETMASK
    gateway $GATEWAY
    dns-nameservers 8.8.8.8 1.1.1.1
EOT

echo "成功: /etc/network/interfaces 文件已生成。"
EOF

# 赋予权限并运行
chmod +x fix_interfaces.sh
sudo ./fix_interfaces.sh
