### ISSUE TITLE
windows 0x0000007B error

### ISSUE THREAD

**Issue by bland3** [MeowLove/Network-Reinstall-System-Modify#30]
can you fix it

**Comment by bland3** [comment]
win 2003 0x0000007B

**Comment by MeowLove** [comment]
缺少详细的反馈信息，无法处理。
不推荐使用旧版操作系统，例如Windows 2003。

The detailed feedback information is missing and cannot be processed.
It is not recommended to use the old operating system, such as Windows 2003.
