### ISSUE TITLE
脚本写推荐centos8，但是网站写推荐centos7，所以更推荐哪个？

### ISSUE THREAD

**Issue by zhanggaoxuan** [MeowLove/Network-Reinstall-System-Modify#31]
脚本写推荐centos8，但是网站写推荐centos7，所以更推荐哪个？

**Comment by MeowLove** [comment]
同上，喜欢那个用哪个，目前2022年7月更推荐，Rocky Linux 8

Same answer as above, which one do you like to use? At present, it is more recommended in July 2022, Rocky Linux 8
