### ISSUE TITLE
Debian 11 已经发布了，考虑跟进吗

### ISSUE THREAD

**Issue by SekiBetu** [MeowLove/Network-Reinstall-System-Modify#33]
Debian 11 已经发布了，考虑跟进吗

**Comment by qianxu2001** [comment]
萌咖的脚本已更新支持 https://github.com/MoeClub/Note

**Comment by wc7086** [comment]
> 萌咖的脚本已更新支持 https://github.com/MoeClub/Note

萌咖的脚本512M内存DD debian11会弹框要求确认进入low memory mode

**Comment by qianxu2001** [comment]
> > 萌咖的脚本已更新支持 https://github.com/MoeClub/Note
> 
> 萌咖的脚本512M内存DD debian11会弹框要求确认进入low memory mode

https://github.com/MoeClub/Note/pull/5#issuecomment-901632821 v佬准备重写脚本了

**Comment by SekiBetu** [comment]
> 萌咖的脚本已更新支持 [MoeClub/Note](https://github.com/MoeClub/Note)

就是不想用萌咖的啊，现在这脚本挺爽的，在各大VPS商上出错率特别低，我从来没遇到过安装错误，萌咖的就遇到过两次了

**Comment by SekiBetu** [comment]
https://github.com/bohanyang/debi
转战debi了，专注debian11，挺好的
