### ISSUE TITLE
请问这个项目是不维护了吗，一直在等debian11

### ISSUE THREAD

**Issue by cncherisher** [MeowLove/Network-Reinstall-System-Modify#34]
用萌咖的脚本各种失败，都d出阴影了
现在这脚本用起来很舒服，在各大VPS商上出错率特别低

**Comment by SekiBetu** [comment]
https://github.com/bohanyang/debi

**Comment by MeowLove** [comment]
已经更新，前一段时间工作太忙

Yes, I was too busy with work some time ago.
