### ISSUE TITLE
dd 失败

### ISSUE THREAD

**Issue by xx13295** [MeowLove/Network-Reinstall-System-Modify#38]
dd centos 系统的时候出现 。服务商为virmach 原因是virmach迁移到 锐龙新平台手贱折腾了一下

![1656040449781](https://user-images.githubusercontent.com/27811560/175454931-da9af315-0216-4f4e-ad5f-e02a19efd761.jpg)

dd debian 无问题。

**Comment by karsacui** [comment]
顺便问一下怎么迁移到ryzen，ryzen migrate那个按钮我本来有的，后来莫名其妙消失找不到了

**Comment by MeowLove** [comment]
网站炸了的情况下，推荐自己保存镜像，手动指定自己的DD镜像的URL。

When the website is blown up, it is recommended to save the image yourself and manually specify the URL of your DD image.
