### ISSUE TITLE
程序不错只是萌咖套壳

### ISSUE THREAD

**Issue by minlearn** [MeowLove/Network-Reinstall-System-Modify#40]
楼主可以加点创意突破性的新功能

**Comment by minlearn** [comment]
望楼主努力，加点真正有用的东西

**Comment by MeowLove** [comment]
在努力更新和新增了。目前Vicer把能做的都做了，套个壳YYDS。

且本项目伊始~至终，明确标注，从萌咖处进行分支。遵从Vicer的要求及GPL协议。

I'm trying to update and add it. At present, Vicer has done everything she can, and set up a shell YYDS.

From the beginning to the end of this project, it is clearly marked and branched from Mengka. Comply with the requirements of Vicer and GPL protocol.
