### ISSUE TITLE
为什么总有人想着靠捐赠来钱

### ISSUE THREAD

**Issue by minlearn** [MeowLove/Network-Reinstall-System-Modify#41]
同等的条件下。有人靠自己的双手光明赚钱，任劳任怨，有人却打起了水滴筹这些工具的主意，靠出卖亲人的惨状来赚钱，想着一夜来钱
不管实与不实，这对普通人来说，公平吗？

----------

翻着支付宝几百几十点偷偷领取捐款的那点面目，不可憎吗？属实穷想钱疯
在后台提取10W几十W的嘴脸，想着来钱这么容易，一边暗喜一边嘲笑别人人傻钱多，不知道有多难看。

比如hostloc上那位
![](https://s3.bmp.ovh/imgs/2022/07/18/8f01130ed4f56259.png)
![](https://s3.bmp.ovh/imgs/2022/07/18/3d8a51b2223efede.png)

**月薪4k求捐20W要钱又要脸又毒又菜hostloc某打包怪natee**

https://hostloc.com/thread-850951-1-1.html
请欣赏natee爽文片断：

> 你们怎么也不敢相信，会喊爸爸妈妈爷爷奶奶的小宝贝，居然患病这么久，才两岁半，就要承受大手术！在身体上开如此多刀！看到他浑身插满管子虚弱地躺在ICU病房里，真希望自己能分担他的痛苦！我现在真是心如刀割!家人也每天以泪洗面！

以下是网友一些评论：

-------

> 月薪4k求捐20W，技术菜，又要钱又要脸，作恶多端，他不倒霉谁倒霉，可怜他孩子帮他受   -----  某网友

> "天爷开眼呐。恶有恶报呗。哭捐作文写真惨专行恶毒陷害之事，恶毒还作恶，很难给这种人共情"   -----  某网友

> 他孩子有多可怜，他这个父亲面目就有多可憎  -----  某网友

> 站在道义上讲我希望他儿子康复，站在他的父亲所作所为来讲，如果可以与他儿子换，我希望他父亲可以双倍承受   -----  某网友

> 每天看一次，把孩子设想为他父亲，心情莫名畅快 ----- 某网友

> 一个男人最怕的不是装B，而是在比他技术还好的人面前装错了B，技不如人话术不如人，还找了个某版主当爹每次都能惯着他，哈哈 ----- 某网友

-------

> 一个人应该靠自己的双手赚钱，而不是拿自己儿子赚钱，背后对一个人凶狠明面对一群人哭穷装狗，翻着支付宝几百几十点偷偷领取捐款的那点面目，不可憎吗？属实穷想钱疯 ----- 某网友

> 一个只会打怪缝合win的人，却去带风陷害一个会写脚本的，人家明码标价光明赚钱，这个却只会点假技术，乞讨哭穷四处，拿儿子揽钱，状如行骗，高下立判。 ----- 某网友

> natee敢不敢来qqvps.com来继续对线 ----- 某网友

**Comment by minlearn** [comment]
11

**Comment by MeowLove** [comment]
请不要在本项目中，牵扯他人事件。谢谢。
CXT永远尊重每一个付出的人，包括大佬你【minlearn】和【NAT.EE】。

Please don't involve other people's events in this project. Thank you.
CXT always respects everyone who gives, including you [minlearn] and [NAT.EE].
