### ISSUE TITLE
【bug】alibabacloud ecs Infinite loop installation

### ISSUE THREAD

**Issue by CodeCrazy-guy** [MeowLove/Network-Reinstall-System-Modify#5]
When I executed your installation script, everything looked fine.

No errors were reported.

I executed the following script to install cents7:
Bash ~/Network-Reinstall-System-Modify.sh -CentOS_7

After the server restarts, it enters an infinite loop of install process.

**Comment by MeowLove** [comment]
Has been repaired. I lost my blog and server before, so it couldn't succeed.

The reason is: when the mirror source can't be connected, the system will keep trying to mirror the source to install the system, but my server explodes and keeps circulating.

MeowLove
