### ISSUE TITLE
what is the user name and password of windows_server_2019?

### ISSUE THREAD

**Issue by Heartbeats1104** [MeowLove/Network-Reinstall-System-Modify#6]
hello, could you tell me what is the user name and password of windows_server_2019 ?

**Comment by MeowLove** [comment]
Hello, usually, when the default image is used, or when the author of your image does not explicitly state the user name and password of the system.

With Microsoft Windows.
The default username is: Administrator
The default password is: cxthhhhh.com

With Linux(CentOS/Debian/Ubuntu).
The default username is: root
The default password is: cxthhhhh.com


您好，通常，使用默认镜像，或者您的镜像作者未明确说明系统的用户名和密码的情况下。

对于Microsoft Windows。
默认的用户名是：Administrator
默认的密码是：cxthhhhh.com

对于Linux（CentOS / Debian / Ubuntu）。
默认的用户名是：root
默认的密码是：cxthhhhh.com

CXT | https://www.cxthhhhh.com
MeowLove
