### ISSUE TITLE
添加 Ubuntu 20.04 LTS (Focal)

### ISSUE THREAD

**Issue by wei** [MeowLove/Network-Reinstall-System-Modify#9]
https://github.com/MeowLove/Network-Reinstall-System-Modify/blob/bbc74cd7d0ef6b57790a4cbf4859f09b1f6de327/CoreShell/Core_Install.sh#L284-L287

上面这里加 20.04 的话下面这行使用 20.04 的话需要把 `/current/images/netboot/...` 改成 `/current/legacy-images/netboot/...`

https://github.com/MeowLove/Network-Reinstall-System-Modify/blob/bbc74cd7d0ef6b57790a4cbf4859f09b1f6de327/CoreShell/Core_Install.sh#L410

**Comment by MeowLove** [comment]
感谢您的帮助，我们已经更新支持Ubuntu20.04。Thank you for your help, we have updated to support Ubuntu20.04.

如果您有任何改进和维修，欢迎继续提交。If you have any improvements and repairs, please submit them.

MeowLove
